#pragma once

#include <Windows.h>

// Dont touch this file; it is auto generated by create_pixel_array.py

const int IMG_WIDTH = 600;
const int IMG_HEIGHT = 600;
const int IMG_COLOR_ARR_LENGTH = 360000;
COLORREF* GetImageColorArray();
